//
//  MainPresenter.swift
//  Foodie
//
//  Created by Gaga Nizharadze on 17.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic
{
    func reloadCollectionViewData()
    func confLocationManager()
    func presentUserNameLabel(username: String)
    func logOut()
//  func presentSomething(response: Main.Something.Response)
}

class MainPresenter: MainPresentationLogic
{
  weak var viewController: MainDisplayLogic?
  
  // MARK: Do something
  
//  func presentSomething(response: Main.Something.Response)
//  {
//    let viewModel = Main.Something.ViewModel()
//    viewController?.displaySomething(viewModel: viewModel)
//  }
    
    func reloadCollectionViewData() {
        viewController?.reloadCollectionView()
    }
    
    func confLocationManager() {
        viewController?.configureLocationManager()
    }
    
    func presentUserNameLabel(username: String) {      // aqac responsi
        let response = Main.Something.Response(username: username)
        viewController?.displayUserName(response: response)
    }
    
    func logOut() {
        viewController?.logOut()
    }
}
