//
//  MainModels.swift
//  Foodie
//
//  Created by Gaga Nizharadze on 17.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Main
{
    // MARK: Use cases
    
    enum Something
    {
        struct Request
        {
            var section: RestaurantsSection
        }
        struct Response
        {
            let username: String
        }
        struct ViewModel
        {
        }
    }
}

enum RestaurantsSection {
    case all
    case top
    case nearby
    case favourite
}
