//
//  SignUpWorker.swift
//  Foodie
//
//  Created by Gaga Nizharadze on 20.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class SignUpWorker {
    
    private var manager: FirebaseManager
    private let validationService = ValidationService()
    
    init(apiManager: FirebaseManager) {
        self.manager = apiManager
    }
    
    var presentErrorAlert: ((String) -> ())?
    var presentSuccessAlert: (() -> ())?
    
    func signUp(email: String?, password: String?, retypedPassword: String?, username: String?) -> SignUpResponses {
        guard let password = password, let email = email, let retypedPass = retypedPassword, let username = username else {
            return .emptyTextField
        }
        
        if password.isEmpty || email.isEmpty || retypedPass.isEmpty || username.isEmpty {
            return .emptyTextField
        }
        if password != retypedPass {
            return .unmatchPassword
        } else if !validationService.isValidPassword(password) {
            return .shortPassword
        }
        else if !validationService.isValidEmail(email) {
            return .invalidMail
        }
        else {
            manager.signUp(with: email, password: password, username: username) { result in
                print(result)
            }
        }
        return .success
    }
    
    enum SignUpResponses: String {
        case emptyTextField = "You have to fill each text field."
        case unmatchPassword = "passwords don't match"
        case shortPassword = "password length should be more than 6 characters"
        case invalidMail = "Invalid Email"
        case success
    }
}
