//
//  SignUpInteractor.swift
//  Foodie
//
//  Created by Gaga Nizharadze on 20.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUpBusinessLogic
{
    func signUp(with request: SignUp.Something.Request)
}

protocol SignUpDataStore {
    var errorMessage: String? { get set }
}

class SignUpInteractor: SignUpBusinessLogic, SignUpDataStore {
    
    var errorMessage: String?
    
    var presenter: SignUpPresentationLogic
    var worker: SignUpWorker
    
    init(presenter: SignUpPresentationLogic, worker: SignUpWorker) {
        self.presenter = presenter
        self.worker = worker
    }
    // MARK: Do something
    
    func signUp(with request: SignUp.Something.Request) {
        let response = worker.signUp(email: request.email, password: request.password, retypedPassword: request.retypedPassword, username: request.username)
        
        switch response {
        case .success:
            presenter.presentSuccessAlertInPreviousVC()
            
        default:
            errorMessage = response.rawValue
            presenter.presentErrorAlert()
        }
    }
}
