//
//  SignUpPresenter.swift
//  Foodie
//
//  Created by Gaga Nizharadze on 17.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUpPresentationLogic {
    func presentErrorAlert()
    func presentSuccessAlertInPreviousVC()
}

class SignUpPresenter: SignUpPresentationLogic {
    weak var viewController: SignUpDisplayLogic?
    
    // MARK: Do something
    
    func presentSuccessAlertInPreviousVC() {
        viewController?.displayPreviousVCWithSuccessAlert()
    }
    
    func presentErrorAlert() {
        viewController?.displayErrorAlert()
    }
}
