//
//  LogInInteractor.swift
//  Foodie
//
//  Created by Gaga Nizharadze on 16.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LogInBusinessLogic
{
    func doSomething(request: LogIn.Something.Request)
}

protocol LogInDataStore
{
//    var emailText: String? { get set }
}

class LogInInteractor: LogInBusinessLogic, LogInDataStore
{
    
    var presenter: LogInPresentationLogic
    var worker: LogInWorkerLogic
//    var emailText: String?
    
    
    init(presenter: LogInPresentationLogic, worker: LogInWorkerLogic) {
        self.presenter = presenter
        self.worker = worker
    }
    // MARK: Do something
    
    
    func doSomething(request: LogIn.Something.Request) {
//        self.emailText = request.emailText
        worker.signIn(emailTextField: request.emailText, passwordTextField: request.passwordText) { [weak self] error in
            if let error = error {
                let response = LogIn.Something.Response(errorMessage: error)
                self?.presenter.prephareForAlertPresentation(response: response)
            } else { self?.presenter.prephareForMovingToMain() }
        }
    }
}
