//
//  LogInModels.swift
//  Foodie
//
//  Created by Gaga Nizharadze on 16.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum LogIn
{
    // MARK: Use cases
    
    enum Something
    {
        struct Request
        {
            var emailText: String?
            var passwordText: String?
        }
        struct Response
        {
            var errorMessage: String
        }
        struct ViewModel
        {
        }
    }
}
