//
//  SignInRouter.swift
//  Foodie
//
//  Created by Gaga Nizharadze on 20.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SignInRoutingLogic {
    func navigateToMainScreen()
    func navigateToSignUpScreen()
}

protocol SignInDataPassing {
  var dataStore: SignInDataStore { get }
}

class SignInRouter: NSObject, SignInRoutingLogic, SignInDataPassing {
  weak var viewController: SignInViewController?
  var dataStore: SignInDataStore
    
    // MARK: - Object Lifecycle
    
    init(dataStore: SignInDataStore) {
        self.dataStore = dataStore
    }
    
    func navigateToMainScreen() {
        let nav = UINavigationController()
        let coordinator = MainViewCoordinator(navigationController: nav)
        coordinator.start()

        viewController?.view.window?.rootViewController = nav
        viewController?.view.window?.makeKeyAndVisible()
    }
    
    func navigateToSignUpScreen() {
        let vc = SignUpConfigurator.configure() as! SignUpViewController
        vc.delegate = viewController
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
}
