//
//  SignInWorker.swift
//  Foodie
//
//  Created by Gaga Nizharadze on 20.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignInWorkerLogic {
    func signIn(emailTextField: String?, passwordTextField: String?, completion: @escaping (String?) -> ())
}

final class SignInWorker: SignInWorkerLogic {
   
    private var manager: FirebaseManager
    
    init(apiManager: FirebaseManager) {
        self.manager = apiManager
    }
    
    // MARK: - Methods
    func signIn(emailTextField: String?, passwordTextField: String?, completion: @escaping (String?) -> ()) {
        guard let email = emailTextField, let password = passwordTextField else {
            completion("You should fill each textfield")
            return
        }
        
        if email.isEmpty || password.isEmpty {
            completion("Fill text fields.")
        }
        else {
            manager.signIn(email: email,password: password) { result in
                switch result {
                case .success(_):
                    completion(nil)
                case.failure(let error):
                    completion(error.localizedDescription)
                }
            }
        }
    }
}
